"""
Django settings for django_cash_flow_manager project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


DatabaseConfig = dict[str, dict[str, object]]


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name: str, default: str = '') -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_str(name: str, default: str) -> str:
    return os.getenv(name, default)


def build_database_config(base_dir: Path) -> DatabaseConfig:
    database_engine = env_str('DATABASE_ENGINE', 'sqlite').lower()

    if database_engine == 'sqlite':
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': base_dir / 'db.sqlite3',
            }
        }

    if database_engine in {'postgres', 'postgresql'}:
        return {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env_str('POSTGRES_DB', 'cash_flow_manager'),
                'USER': env_str('POSTGRES_USER', 'cash_flow_user'),
                'PASSWORD': env_str('POSTGRES_PASSWORD', 'cash_flow_password'),
                'HOST': env_str('POSTGRES_HOST', 'db'),
                'PORT': env_str('POSTGRES_PORT', '5432'),
            }
        }

    message = f'Unsupported DATABASE_ENGINE={database_engine!r}. Use sqlite or postgresql.'
    raise ImproperlyConfigured(message)


# Пути внутри проекта строятся так: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Быстрые настройки для разработки, не предназначены для production.
# Подробнее: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Важно: production-секретный ключ должен храниться вне кода.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-development-key')

# Важно: не включать DEBUG в production.
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')


# Подключенные Django-приложения

INSTALLED_APPS = [
    'django_cash_flow_manager.devtools',
    'django_cash_flow_manager.cashflows',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_cash_flow_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_cash_flow_manager.wsgi.application'


# База данных
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = build_database_config(BASE_DIR)


# Валидация паролей
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Локализация
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Статические файлы: CSS, JavaScript, изображения
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
